server:
  port: 8081

spring:
  application:
    name: appointment-service
  
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  h2:
    console:
      enabled: true

# Kafka disabled for standalone mode
logging:
  level:
    com.mediwave.appointment: DEBUG
